genres/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('register/',views.UserFormView.as_view(),name="userform"),
    path('',views.genres_view.as_view(),name="genres"),
    path('<pk>/',views.details.as_view(),name="details"),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('genres.urls')),
    path('admin/', admin.site.urls),
]

genres/models.py
from django.db import models
class coll(models.Model):
    collName = models.CharField(max_length=100)
    collDesc = models.CharField(max_length=500)
    collCover = models.CharField(max_length=1000)

    def __str__(self):
        return self.collName

class piece(models.Model):
    Coll = models.ForeignKey(coll,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    year = models.IntegerField()
    pieceCover = models.CharField(max_length=1000)

    def __str__(self):
        return self.title


# Create your models here.

genres/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

genres/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import coll,piece
from django.views import generic
from .forms import UserForm
from django.contrib.auth import authenticate,login
from django.views.generic import View

class genres_view(generic.ListView):
    template_name = "genres/genresTemplates.html"

    def get_queryset(self):
        return coll.objects.all()

class details(generic.DetailView):
    model = coll
    template_name = "genres/detailsTemplates.html"

class UserFormView(View):
    formCls = UserForm
    templateName = "genres/formTemplate.html"

    def get(self,request):
        form = self.formCls(None)
        return render(request,self.templateName,{'form':form})
    
    def post(self,request):
        form = self.formCls(request.POST)

        if form.is_valid():
            user = form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            newUser = authenticate(username=username,password=password)

            if newUser is not None:
                if newUser.is_active:
                    login(request,newUser)  
                    return redirect("/genres")
        return render(request,self.templateName,{'form':form})

genres/templates/genres/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:image" content="" />
        <title>Genres</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'genres' %}">Home</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'userform' %}">
                            Register
                        </a>
                    </li>
                    <li class="">
                        <a>{{request.user}}</a>
                    </li>
                </ul>
            </div>
        </nav>
{% block content %}
{% endblock %}
    </body>
</html>

genres/templates/genres/detailsTemplates.html
{% extends 'genres/base.html' %}
{% block content %}
{% for j in coll.piece_set.all %}
<div align="center">
    <img src="{{j.pieceCover}}" alt="image" height="200" width="200">
    <h2>{{j.title}} - {{j.artist}}</h2>
    <h3>{{j.type}}</h3>
    <h3>{{j.year}}</h3><br/>
</div>
{% endfor %}
<<<<<<< HEAD
{% endblock %}
=======
{% endblock %}
>>>>>>> 1d88d0e99d5c0ac83302d54677e8735ee7f297ed

genres/templates/genres/formTemplate.html
{% extends 'genres/base.html' %}    
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    Username:
    <input type="text" title="uname" name="username"></br>
    
    Email:
    <input type="text" title="mail" name="email"></br>
    
    Password:
    <input type="password" title="pass" name="password"></br>
    
    <input type="submit" value="submit">
</form> 
<<<<<<< HEAD
{% endblock %}
=======
{% endblock %}
>>>>>>> 1d88d0e99d5c0ac83302d54677e8735ee7f297ed

genres/templates/genres/genresTemplates.html
{% extends 'genres/base.html' %}
{% block content %}
{% for i in object_list %}
<div align="center">
    <img src="{{i.collCover}}" alt="images" height="200" width="200">
    <h2><a href="{% url 'details' pk=i.id %}">{{i.collName}}</a></h2>
    <h3>{{i.collDesc}}</h3><br/>
</div>
{% endfor %}
<<<<<<< HEAD
{% endblock %}
=======
{% endblock %}
>>>>>>> 1d88d0e99d5c0ac83302d54677e8735ee7f297ed